Update HMM.py
Fixes the following error due to trying to index with a float 
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

in python 3.8 numpy 1.20.2